### PR TITLE
Enoc/upgrade pod security standard to restricted level

### PR DESCRIPTION
**Pull request by enocquet**
Set the pod policy to restricted by default, following current Pod hardening best practices. 
https://kubernetes.io/docs/concepts/security/pod-security-standards/

### CODE REVIEW

**Review by sjoubert — COMMENTED** [review]
From what I understand, if the various applications can work with these restrictions then these are good security measures. Does/should it work on AKS by default too?

**Review by sjoubert — CHANGES_REQUESTED** [review]
We are probably missing the same config on RabbitMQ

**Comment by enocquet** [comment]
> From what I understand, if the various applications can work with these restrictions then these are good security measures. Does/should it work on AKS by default too?

It should. Nothing really changes outside of the cluster

**Comment by enocquet** [comment]
> We are probably missing the same config on RabbitMQ

No. It is defined with low level permissions by default

**Review by sjoubert — APPROVED** [review]

**Pull request merged**
